# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import errors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(help_text='Artist name. Required.', max_length=200, unique=True)),
                ('artist_url', models.URLField(blank=True, help_text='Artist homepage or whatever. Not required.')),
                ('slug', models.SlugField(default='', help_text="Long and mystrious auto-generated slug. This is the 'URL' for this page, and the directory where its assets will be uploaded.", unique=True)),
                ('content', models.TextField(help_text='The ENTIRE HTML for the page. You\'ll need to reference static assets like src="/media/[slug]/[asset].gif" SAVE THIS RECORD FIRST TO UPLOAD FILES AND SEE THE SLUG. Then change the HTML. Yea it\'s silly. Required.')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorArtFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_file', models.FileField(upload_to=errors.models.ErrorArtFile.get_slug_path)),
                ('error_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='errors.ErrorArt')),
            ],
        ),
    ]
