# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorart',
            name='show_in_gallery_mode',
            field=models.BooleanField(default=1, help_text='Uncheck to hide when Gallery Mode is enabled. Gallery Mode is currently: <strong>Enabled</strong>'),
        ),
    ]
