# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0002_errorart_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorart',
            name='artist_url',
            field=models.URLField(blank=True, help_text='Artist homepage or whatever. Not required.'),
        ),
        migrations.AlterField(
            model_name='errorart',
            name='artist',
            field=models.CharField(help_text='Artist name. Required', max_length=200),
        ),
        migrations.AlterField(
            model_name='errorart',
            name='content',
            field=models.TextField(help_text="Everything appearing between the <body></body> tags of our html. We'll figure out static assets later. Required."),
        ),
        migrations.AlterField(
            model_name='errorart',
            name='slug',
            field=models.SlugField(help_text="The part of the URL we want to be able to link this 404 error from, without the slash. Ex: A value of 'my-404-page' would resolve to http://404error.gallery/my-404-page. Required."),
        ),
        migrations.AlterField(
            model_name='errorart',
            name='title',
            field=models.CharField(blank=True, help_text='The title as it appears on our homepage list. Not required.', max_length=200),
        ),
    ]
