# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0003_auto_20161119_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorart',
            name='artist',
            field=models.CharField(help_text='Artist name. Required.', max_length=200),
        ),
        migrations.AlterField(
            model_name='errorart',
            name='content',
            field=models.TextField(help_text='The ENTIRE HTML for the page. You\'ll need to add static assets to the appropriate errors/static/* folder and reference them like src="/static/errors/img/[asset].gif" Required.'),
        ),
    ]
